services:
  db:
    image: postgres:14.1-alpine
    restart: on-failure
    environment:
      - POSTGRES_DB=iotm2
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5454:5432
    volumes:
      - db:/var/lib/postgresql/data

  admin:
    image: adminer
    restart: on-failure
    depends_on: 
      - db
    ports:
      - 8787:8080

volumes:
  db:
    driver: local
  cache:
    driver: local