apiVersion: v1
kind: Service
metadata:
  name: postgresql-cluster-remote
  labels:
    postgresql: postgresql-cluster
spec:
  selector:
    postgresql: postgresql-cluster
    role: primary
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432