
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{cookiecutter.project_slug}}
  name: {{cookiecutter.project_slug}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{cookiecutter.project_slug}}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{cookiecutter.project_slug}}
    spec:
      containers:
      - image: $APP_IMAGE
        name: {{cookiecutter.project_slug}}
        resources:
          limits:
            memory: 600Mi
            cpu: 1
          requests:
            memory: 300Mi
            cpu: 500m
        ports:
          - containerPort: 8080
            name: http
        env:
          - name: DATABASE_URL
            value: "$DATABASE_URL"
          - name: REDIS_URL
            value: "$REDIS_URL"
          - name: JWT_SECRET_KEY
            value: "$JWT_SECRET_KEY"
          - name: JWT_ALGORITHM
            value: "$JWT_ALGORITHM"
          - name: JWT_ACCESS_TOKEN_EXPIRE_MINUTES
            value: "$JWT_ACCESS_TOKEN_EXPIRE_MINUTES"
      dnsPolicy: ClusterFirst